"""before deployment

Revision ID: 4811e178166e
Revises: None
Create Date: 2016-07-17 10:21:28.896286

"""

# revision identifiers, used by Alembic.
revision = '4811e178166e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
